### ISSUE TITLE
Log Progress

### ISSUE THREAD

**Issue by gweit** [engina/dropbox2#2]
Sorry fot bothering you, is there any way i can log the stats in the console during the sync?

Best, Gernot

**Comment by engina** [comment]
Hello Gernot,

User class fires a sync-file-downloaded event also has a stats property with detailed stats.

You can handle the event and print the file that is just downloaded and/or go into more details with the stats object if you want.

You can try checking the unit tests, that might help also: https://github.com/engina/dropbox2/blob/master/spec/userSpec.js#L123-L145

Does that work for you?

**Comment by gweit** [comment]
Hi Engin,

Thank You very much, i´ll try that out ;)


Best, Gernot

**Comment by engina** [comment]
Assuming things worked out for you. Closing the issue. Feel free to re-open.
